### PR TITLE
fix: resolve research plan table column renaming and short label link…

### LINKED ISSUE #2594: Line Break in Table of Research Plan
- I am an ELN admin

# Description
At the moment there is no line break in tables (in the research plan) if the content of a cell is longer than the cell. This leads to the effect that you can not read the whole content of a cell in view mode. (See picture)

Image

This is necessary to improve the usage of the research plan, since more and more people are starting to improve their documentation. Specially when collaborating with other researchers of the research group.

(Screenshot is taken from Chemotion ELN v2.0.1)

### LINKED ISSUE #2624: renaming column with link to short label sample or reaction in research plan table

### PR DESCRIPTION
**Pull request by alizaib1217**
feat(research-plans): Add short label linking and fix modal state bugs in table component

## Overview

https://github.com/user-attachments/assets/ae693fc7-ba4e-48a7-a2d2-b41c64210f38

This PR enhances the Research Plan table component with clickable short label linking functionality and fixes critical modal state management bugs. Additionally, it improves code quality by addressing ESLint violations and removing dead code.

### Short Label Linking System
- Sample Linking: Columns can now be configured to render sample short labels as clickable links
- Any text other than specific reaction and sample can now be made short label link
- Reaction Linking: Columns can now be configured to render reaction short labels as clickable links
- Navigation Integration: Clicking links navigates directly to the corresponding sample/reaction pages
- Link Type Validation: Prevents creation of duplicate link columns (only one sample column and one reaction column allowed)

### Enhanced Column Management
- Improved column creation modal with linking options
- Enhanced column rename functionality with link type management
- Visual link indicators with proper styling (cursor: pointer, link styling)
- Line break for long text in cell

### Modal State Management
- Fixed Issue #2624: Modal checkboxes now correctly reflect the action being performed
- Insert vs Rename Logic: Modal no longer shows incorrect checkbox state when switching between insert and rename actions
- State Isolation: Proper separation of modal state between different operations

### Constructor Logic
- Fixed constructor to properly handle insert vs rename actions
- Resolved modal state contamination issues between different column operations

### ESLint Compliance
- Fixed all "Must use destructuring props assignment" violations
- Fixed all "Must use destructuring state assignment" violations
- Implemented proper destructuring patterns throughout the component

### Dead Code Removal
- Removed unused legacy functions from React Data Grid era:
  - handleColumnDelete (replaced by removeThisColumn)
  - handleColumnResize (replaced by ag-Grid event handlers)
  - handleRowInsert (replaced by addNewRow)
  - handleRowDelete (replaced by removeThisRow)
- Removed unused state fields and properties
- Cleaned up obsolete references and imports

## Code Review Focus Areas
1. Modal Logic: Verify insert vs rename state management
2. Link Functionality: Test sample/reaction navigation
3. Destructuring: Confirm ESLint compliance
4. Error Handling: Review graceful failure scenarios
5. State Management: Validate ag-Grid integration

## Related Issues
- Fixes #2624 (Research plan table modal state bug)
- Fixes #2594 (Line Break in Research Plan)
- Addresses destructuring ESLint violations
- Removes dead code from React Data Grid migration (commit ee97f3684)

------------------------------------------------------

### CODE REVIEW

File: app/javascript/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldTable.js [hunk 1]
```diff
@@ -35,41 +39,23 @@ export default class ResearchPlanDetailsFieldTable extends Component {
...
-      key: id,
-      name: columnName,
-      resizable: true,
-      width: 200,
-    };
-  }
-
-  buildRow() {
-    return [];
+  componentWillUnmount() {
```
Comment (haditariq) [inline app/javascript/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldTable.js]: There is no initialization of clipboardTimeout in this file except here.

File: app/javascript/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldTable.js [hunk 2]
```diff
@@ -104,72 +91,142 @@ export default class ResearchPlanDetailsFieldTable extends Component {
...
       this.setState({
         schemaModal: {
           show: true,
-          schemas: json['table_schemas']
+          schemas: json.table_schemas
         }
       });
     });
+  };
+
```
Comment (haditariq) [inline app/javascript/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldTable.js:138]: extra lines

File: app/javascript/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldTableColumnNameModal.js [hunk 3]
```diff
@@ -21,13 +34,35 @@ class ResearchPlanDetailsFieldTableColumnNameModal extends Component {
...
+          columnNameValue = currentColumn.headerName;
+          // Check if this column currently has linking functionality
+          linkSampleShortLabel = currentColumn.linkType === 'sample';
+          linkReactionShortLabel = currentColumn.linkType === 'reaction';
+        }
       }
+      // For 'insert' action, keep checkboxes unchecked - this is correct behavior
+
+      // Simple availability check: only one of each link type allowed
+      const sampleColumnExists = columns.some((col) => col.linkType === 'sample');
```
Comment (haditariq) [inline app/javascript/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldTableColumnNameModal.js]: It would be better if we can define sample and reaction as variables because they are used alot of times for example const COLUMN_TYPE_SAMPLE = 'sample'; and change for other files used in this PR if possible.

File: app/javascript/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldTable.js [hunk 4]
```diff
@@ -365,19 +427,17 @@ export default class ResearchPlanDetailsFieldTable extends Component {
...
-        field.value.rows = rowData
+        field.value.rows = rowData;
         onChange(field.value, field.id);
       })
-      .catch(err => {
+      .catch((err) => {
         console.error('Failed to read clipboard contents: ', err);
       });
-  }
+  };
```
Comment (haditariq) [inline app/javascript/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldTable.js:428]: This file has to many indenting changes and eslint fixes. Probably good for another PR.

**Review by haditariq — CHANGES_REQUESTED** [review]
@alizaib1217 the feature looks good. thanks!

Minor changes requested. If you plan to remove eslint changes specially from this [file](https://github.com/ComPlat/chemotion_ELN/blob/c845c0c2062ea0b0f662ffd5d597b78817a274c0/app/javascript/src/apps/mydb/elements/details/researchPlans/researchPlanTab/ResearchPlanDetailsFieldTable.js). I would be happy to look at this file again.

squashing the commits would be nice as well.

**Comment by alizaib1217** [comment]
Hi @haditariq ,
Thanks for the feedback. I have done the requested changes. Have a look.
